---

- name: Slurp connection-string.txt content
  ansible.builtin.slurp:
    src: "{{ role_path }}/../../connection-strings.txt"
  register: connection_strings
  delegate_to: localhost
  become: false

- name: Include webtunnel testing task
  ansible.builtin.include_tasks: webtunnel-testing.yaml 
  loop: "{{ connection_strings['content'] | b64decode | split('\n') }}"
  loop_control:
    extended: true

- name: Collect all debug messages
  ansible.builtin.set_fact:
    all_debug_messages: "{{ groups['all'] | map('extract', hostvars, 'tor_debug_messages') | select('defined') | flatten }}"

- name: Display all debug messages at the end
  ansible.builtin.debug:
    msg: "{{ all_debug_messages }}"
  run_once: true

- name: Shutdown webtunnel-client
  community.general.shutdown: