---

- name: Slurp connection-string.txt content
  ansible.builtin.slurp:
    src: "{{ role_path }}/../../connection-strings.txt"
  register: connection_strings
  delegate_to: localhost

- name: Serve HTTP-503
  ansible.builtin.copy:
    src: "{{ role_path }}/files/503.conf"
    dest: /etc/nginx/http.d/503.conf

- name: Unerve HTTP-200
  ansible.builtin.file:
    path: /etc/nginx/http.d/200.conf
    state: absent

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: Include webtunnel testing task
  ansible.builtin.include_tasks: webtunnel-testing.yaml 
  loop: "{{ connection_strings['content'] | b64decode | split('\n') }}"
  loop_control:
    extended: true

- name: Serve HTTP-200
  ansible.builtin.copy:
    src: "{{ role_path }}/files/200.conf"
    dest: /etc/nginx/http.d/200.conf

- name: Unerve HTTP-503
  ansible.builtin.file:
    path: /etc/nginx/http.d/503.conf
    state: absent

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: Display all Tor test results
  ansible.builtin.debug:
    msg: "{{ webtunnel_test_result }}"