---

- name: Add block for empty item check
  when: not item == ""
  block:
    - name: Generate torrc file
      ansible.builtin.template:
        src: "{{ role_path }}/templates/torrc.j2"
        dest: /etc/tor/torrc 

    - name: Restart tor service
      ansible.builtin.service:
        name: tor
        state: restarted

    - name: Wait for SOCKS5-Port to be available
      ansible.builtin.wait_for:
        port: 1080
        timeout: 30
      register: socks_port_check

    - name: Test tor connection
      ansible.builtin.command: curl -sS --socks5 localhost:1080 https://check.torproject.org/api/ip
      register: tor_result

    - name: Set IsTor fact
      ansible.builtin.set_fact:
        isTor: "{{ tor_result.stdout | from_json | json_query('IsTor') }}"

    - name: Append debug message to list
      ansible.builtin.set_fact:
        webtunnel_test_result: "{{ debug_messages | default([]) + [item | regex_replace('.*#', '') ~ ': ' ~ isTor | string] }}"

    - name: Fail if IsTor is false
      ansible.builtin.fail:
        msg: "Tor connection failed for node {{ item | regex_replace('.*#', '') }}"
      when: isTor == false