---

- name: Validate caddy
  ansible.builtin.command:
    cmd: caddy validate --config {{ webserver_config[use_webserver].config_dir }}/Caddyfile
  register: caddy_validate
  notify:
    - Restart caddy
  changed_when: false

- name: Validate nginx
  ansible.builtin.command:
    cmd: nginx -t
  register: nginx_validate
  notify:
    - Restart nginx
  changed_when: false

- name: Validate apache
  ansible.builtin.command:
    cmd: apachectl configtest
  register: apache_validate
  notify:
    - Restart apache
  changed_when: false

- name: Restart caddy
  ansible.builtin.service:
    name: "{{ webserver_config[use_webserver].service_name }}"
    state: "{{ item }}"
    enabled: true
  async: 120
  poll: 5
  when: caddy_validate is success
  loop:
    - started
    - restarted

- name: Restart nginx
  ansible.builtin.service:
    name: "{{ webserver_config[use_webserver].service_name }}"
    state: "{{ item }}"
    enabled: true
  async: 120
  poll: 5
  when: nginx_validate is success
  loop:
    - started
    - restarted

- name: Restart apache
  ansible.builtin.service:
    name: "{{ webserver_config[use_webserver].service_name }}"
    state: "{{ item }}"
    enabled: true
  async: 120
  poll: 5
  when: apache_validate is success
  loop:
    - started
    - restarted

- name: Restart portacl
  ansible.builtin.service:
    name: portacl
    state: restarted
    enabled: true
