---

- name: Start caddy
  ansible.builtin.service:
    name: caddy
    state: started
    enabled: true

- name: Restart caddy
  ansible.builtin.service:
    name: caddy
    state: restarted
    enabled: true

- name: Start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true

- name: Start apache
  ansible.builtin.service:
    name: "{{ system.apache.service_name }}"
    state: started
    enabled: true

- name: Restart apache
  ansible.builtin.service:
    name: "{{ system.apache.service_name }}"
    state: restarted
    enabled: true