---

- name: Start caddy
  ansible.builtin.service:
    name: "{{ webserver_config[use_webserver].service_name }}"
    state: started
    enabled: true
  async: 120
  poll: 5 
  ignore_errors: true

- name: Restart caddy
  ansible.builtin.service:
    name: "{{ webserver_config[use_webserver].service_name }}"
    state: restarted
    enabled: true
  async: 120
  poll: 5 
  ignore_errors: true

- name: Start nginx
  ansible.builtin.service:
    name: "{{ webserver_config[use_webserver].service_name }}"
    state: started
    enabled: true
  async: 120
  poll: 5 
  ignore_errors: true

- name: Restart nginx
  ansible.builtin.service:
    name: "{{ webserver_config[use_webserver].service_name }}"
    state: restarted
    enabled: true
  async: 120
  poll: 5 
  ignore_errors: true

- name: Start apache
  ansible.builtin.service:
    name: "{{ webserver_config[use_webserver].service_name }}"
    state: started
    enabled: true
  async: 120
  poll: 5 
  ignore_errors: true

- name: Restart apache
  ansible.builtin.service:
    name: "{{ webserver_config[use_webserver].service_name }}"
    state: restarted
    enabled: true
  async: 120
  poll: 5 
  ignore_errors: true

- name: Restart portacl
  ansible.builtin.service:
    name: portacl
    state: restarted
    enabled: true