---

- name: Validate caddy
  ansible.builtin.command: 
    cmd: caddy validate --config {{ webserver_config[use_webserver].config_dir }}/Caddyfile
  register: caddy_validate
  notify:
    - Start caddy

- name: Validate nginx
  ansible.builtin.command: 
    cmd: nginx -t
  register: nginx_validate
  notify:
    - Start nginx

- name: Validate apache
  ansible.builtin.command: 
    cmd: apachectl configtest
  register: apache_validate
  notify:
    - Start apache

- name: Start caddy
  ansible.builtin.service:
    name: "{{ webserver_config[use_webserver].service_name }}"
    state: started
    enabled: true
  async: 120
  poll: 5 
  ignore_errors: true
  when:
    - caddy_validate is success
  notify:
    - Restart caddy

- name: Restart caddy
  ansible.builtin.service:
    name: "{{ webserver_config[use_webserver].service_name }}"
    state: restarted
    enabled: true
  async: 120
  poll: 5 
  ignore_errors: true
  when:
    - caddy_validate is success

- name: Start nginx
  ansible.builtin.service:
    name: "{{ webserver_config[use_webserver].service_name }}"
    state: started
    enabled: true
  async: 120
  poll: 5 
  ignore_errors: true
  when:
    - nginx_validate is success
  notify:
    - Restart nginx

- name: Restart nginx
  ansible.builtin.service:
    name: "{{ webserver_config[use_webserver].service_name }}"
    state: restarted
    enabled: true
  async: 120
  poll: 5 
  ignore_errors: true
  when:
    - nginx_validate is success

- name: Start apache
  ansible.builtin.service:
    name: "{{ webserver_config[use_webserver].service_name }}"
    state: started
    enabled: true
  async: 120
  poll: 5 
  ignore_errors: true
  when:
    - apache_validate is success
  notify:
    - Restart apache

- name: Restart apache
  ansible.builtin.service:
    name: "{{ webserver_config[use_webserver].service_name }}"
    state: restarted
    enabled: true
  async: 120
  poll: 5 
  ignore_errors: true
  when:
    - apache_validate is success

- name: Restart portacl
  ansible.builtin.service:
    name: portacl
    state: restarted
    enabled: true