---

- name: Provision/Deprovision test server
  hosts: bhyve-host
  become: true
  roles:
    - role: bhyve

- name: Test the webtunnel
  hosts: webtunnel_clients
  become: true
  tags:
    - never
    - test-webtunnel
  roles:
    - role: test-webtunnel