---

- name: Provision/Deprovision test server
  hosts: bhyve-host
  become: true
  roles:
    - role: bhyve

- name: Shutdown
  hosts: webtunnel-client
  become: yes
  tags:
    - never
    - test-webtunnel
  roles:
    - role: test-webtunnel