---

collections:
  - name: community.general
  - name: hetzner.hcloud
  - name: ansible.posix
  - name: community.docker
# For git dependency:
#   - name: https://github.com/some/repository
#     type: git
