---

- name: Check if OS-specific vars exist
  ansible.builtin.stat:
    path: "{{ role_path }}/vars/{{ ansible_os_family }}.yaml"
  delegate_to: localhost
  become: false
  register: os_vars

- name: Load OS-specific vars
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_distribution }}.yaml'
        - '{{ ansible_os_family }}.yaml'
        - main.yaml
      paths:
        - '{{ role_path }}/vars'
  when: os_vars.stat.exists

- name: Include firewall
  ansible.builtin.include_tasks: firewall.yaml
