---

- name: Install required packages on FreeBSD
  ansible.builtin.package:
    name:
      - "{{ item }}"
    state: present
  loop: security.packages

- name: Load mac_bsdextended module on FreeBSD
  ansible.posix.sysctl:
    name: security.mac.bsdextended.enable
    value: 1
    state: present
    reload: true

- name: Enable MAC (mac_bsdextended) in /boot/loader.conf
  ansible.builtin.lineinfile:
    path: /boot/loader.conf
    regexp: '^security.mac.bsdextended.enable'
    line: 'security.mac.bsdextended.enable=1'

- name: Set MAC policy for Tor data directory
  ansible.posix.sysctl:
    name: security.mac.bsdextended.tor_directory
    value: "{{ tor.directory }}"
    state: present
    reload: true

- name: Set MAC policy for Tor configuration files
  ansible.posix.sysctl:
    name: security.mac.bsdextended.tor_config
    value: "{{ system.etc }}/tor"
    state: present
    reload: true

- name: Set MAC policy for WebTunnel binary
  ansible.posix.sysctl:
    name: security.mac.bsdextended.webtunnel
    value: /usr/local/bin/webtunnel
    state: present
    reload: true

- name: Allow Tor to bind to WebTunnel port 15000
  ansible.posix.sysctl:
    name: security.mac.bsdextended.tor_port_15000
    value: 1
    state: present
    reload: true

- name: Enable mac_bsdextended module
  ansible.posix.sysctl:
    name: security.mac.bsdextended.enable
    value: 1
    state: present
    reload: true

- name: Set MAC policies for Tor and {{ use_webserver }}
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  loop:
    - { name: "security.mac.bsdextended.tor_directory", value: "{{ tor.directory }}" }
    - { name: "security.mac.bsdextended.{{ use_webserver }}_directory", value: "{{ webserver.webroot }}" }
    - { name: "security.mac.bsdextended.{{ use_webserver }}_log", value: "{{ webserver_config[use_webserver].error_log }}" }
