---

- name: Install SELinux on RHEL/CentOS/AlmaLinux
  when: ansible_facts.os_family == 'RedHat'
  yum:
    name:
      - selinux-policy
      - selinux-policy-targeted
      - policycoreutils
    state: present

- name: Install SELinux on Ubuntu/Debian
  when: ansible_facts.os_family == 'Debian'
  apt:
    name:
      - selinux-utils
      - policycoreutils
    state: present
    update_cache: yes

- name: Enable SELinux
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=enforcing'
    create: yes

- name: Set SELinux to Enforcing Mode
  command: setenforce 1
  ignore_errors: yes

# Step 2: Install and Enable Tor
- name: Install Tor
  package:
    name: tor
    state: present

- name: Enable and Start Tor Service
  service:
    name: tor
    state: started
    enabled: yes

# Step 3: Configure SELinux for Tor WebTunnel
- name: Set SELinux context for Tor data directory
  community.general.sefcontext:
    target: "/var/lib/tor(/.*)?"
    setype: tor_var_lib_t
    state: present

- name: Set SELinux context for Tor configuration files
  community.general.sefcontext:
    target: "/etc/tor(/.*)?"
    setype: tor_etc_t
    state: present

- name: Set SELinux context for Tor hidden service directories
  community.general.sefcontext:
    target: "/var/lib/tor/hidden_service(/.*)?"
    setype: tor_var_lib_t
    state: present

- name: Set SELinux context for Tor logs
  community.general.sefcontext:
    target: "/var/log/tor(/.*)?"
    setype: tor_log_t
    state: present

- name: Apply SELinux file context changes for Tor
  command: restorecon -Rv /var/lib/tor /etc/tor /var/log/tor

# Step 4: Configure SELinux for WebTunnel Binary
- name: Set SELinux context for WebTunnel binary
  community.general.sefcontext:
    target: "/usr/local/bin/webtunnel"
    setype: tor_exec_t
    state: present

- name: Allow WebTunnel binary to execute
  command: restorecon -Rv /usr/local/bin/webtunnel

# Step 5: Allow Tor to Bind to WebTunnel Port 15000
- name: Allow Tor to bind to WebTunnel port 15000
  command: semanage port -a -t tor_port_t -p tcp 15000
  ignore_errors: yes

- name: Allow Tor to communicate with web servers
  command: setsebool -P httpd_can_network_connect 1

# Step 6: Configure SELinux for Web Servers (Apache/Nginx/Caddy)
- name: Set SELinux context for Web Server Reverse Proxy Directories
  community.general.sefcontext:
    target: "/var/www/html(/.*)?"
    setype: httpd_sys_rw_content_t
    state: present

- name: Allow Web Server to Connect to Tor WebTunnel
  command: setsebool -P httpd_can_network_relay 1

- name: Apply SELinux file context changes for Web Servers
  command: restorecon -Rv /var/www/html /etc/nginx /etc/httpd /etc/caddy

# Step 7: Reboot System to Apply SELinux Changes
- name: Reboot system to apply changes
  reboot:
    reboot_timeout: 600
  when: ansible_facts.os_family != 'Alpine'
