---

- name: Install required packages
  ansible.builtin.package:
    name:
      - "{{ item }}"
    state: present
  loop: security.packages

- name: Enable Systrace
  ansible.builtin.shell:
    cmd sysctl kern.systrace_enabled=1
  ignore_errors: yes
  notify: Restart system

- name: Create Systrace policy directory
  ansible.builtin.file:
    path: "{{ system.etc }}/systrace"
    state: directory
    mode: '0755'

- name: Generate Systrace policies for Tor
  ansible.builtin.template:
    src: "{{ role_path }}/templates/tor.systrace.j2"
    dest: "{{ system.etc }}/systrace/tor"
    owner: "{{ root.user }}"
    group: "{{ root.group }}"
    mode: '0644'

- name: Generate Systrace policies for WebTunnel
  ansible.builtin.template:
    src: "{{ role_path }}/templates/webtunnel.systrace.j2"
    dest: "{{ system.etc }}/systrace/webtunnel"
    owner: "{{ root.user }}"
    group: "{{ root.group }}"
    mode: '0644'

- name: Apply Systrace policies for Tor
  ansible.builtin.shell:
    cmd: systrace -a -c {{ system.etc }}/systrace/tor /usr/local/bin/tor
  notify: Restart system

- name: Apply Systrace policies for WebTunnel
  ansible.builtin.shell:
    cmd: systrace -a -c {{ system.etc }}/systrace/webtunnel /usr/local/bin/webtunnel
  notify: Restart system