---

- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
    enabled: true

- name: Restart containers
  ansible.builtin.command:
    cmd: docker compose -f {{ docker.directory }}/docker-compose.yml down --remove-orphans && docker compose -f {{ docker.directory }}/docker-compose.yml up -d
  changed_when: true # True, so restart handler is triggered
  notify: Request SSL-Certificate

- name: Request SSL-Certificate
  ansible.builtin.command:
    cmd: docker compose exec -f {{ docker.directory }}/docker-compose.yml certbot certonly --webroot -w /var/www/certbot -d {{ domain }} --cert-name {{ domain }} --email {{ email }} --non-interactive --agree-tos
  changed_when: "'Certificate not yet due for renewal' not in certbot_output.stdout"
