---
root:
  user: root
  group: wheel

webserver:
  user: >-
    {%- if use_webserver == "caddy" -%}
      caddy
    {%- elif use_webserver == "nginx" -%}
      nginx
    {%- elif use_webserver == "apache" -%}
      apache
    {%- else -%}
      www-data
    {%- endif -%}
  group: >-
    {%- if use_webserver == "caddy" -%}
      caddy
    {%- elif use_webserver == "apache" -%}
      apache
    {%- else -%}
      www-data
    {%- endif -%}

system:
  packages:
    - apache2
    - certbot
    - apache2-ctl
    - apache2-ssl
    - apache2-proxy
  caddy:
    config_dir: /etc/caddy
  nginx:
    config_dir: nginx/http.d
  apache:
    service_name: apache2
    config_dir: /etc/apache2/conf.d
    config_file: /etc/apache2/httpd.conf
    modules:
      - LoadModule ssl_module libexec/apache24/mod_ssl.so
      - LoadModule proxy_module libexec/apache24/mod_proxy.so
      - LoadModule headers_module libexec/apache24/mod_headers.so
    modules_disable: []
  certbot:
    config_dir: /etc/letsencrypt