---
root:
  user: root
  group: wheel

webserver:
  user: >-
    {%- if use_webserver == "caddy" -%}
      caddy
    {%- elif use_webserver == "nginx" -%}
      http
    {%- else -%}
      www-data
    {%- endif -%}
  group: >-
    {%- if use_webserver == "caddy" -%}
      caddy
    {%- else -%}
      http
    {%- endif -%}

system:
  etc: /etc
  nginx:
    config_dir: http.d
  certbot_package: certbot