---
root:
  user: root
  group: root
webserver:
  user: >-
    {%- if use_webserver == "caddy" -%}
      caddy
    {%- else -%}
      www-data
    {%- endif -%}
  group: >-
    {%- if use_webserver == "caddy" -%}
      caddy
    {%- else -%}
      www-data
    {%- endif -%}
  webroot: /var/www/html
system:
  etc: /etc
webserver_config:
  caddy:
    service_name: caddy
    config_dir: /etc/caddy
    extra_dirs: /etc/caddy/configs
    error_log: /var/log/caddy-error.log
  nginx:
    packages:
      - nginx
      - certbot
    service_name: nginx
    config_dir: /etc/nginx/sites-enabled
    error_log: /var/log/nginx-error.log
  apache:
    packages:
      - apache2
      - certbot
    service_name: apache2
    server_root: /etc/apache2
    config_dir: /etc/apache2/sites-enabled
    config_file: /etc/apache2/apache2.conf
    extra_dirs: []
    error_log: /var/log/httpd-error.log
    modules:
      - rewrite
      - ssl
      - proxy_http
      - headers
    modules_config:
      - IncludeOptional mods-enabled/*.load
      - IncludeOptional mods-enabled/*.conf
certbot:
  config_dir: /etc/letsencrypt
  webroot: /var/www/certbot
tor:
  directory: /var/lib/tor
