---
root:
  user: root
  group: wheel

webserver:
  user: >-
    {%- if use_webserver == "caddy" -%}
      caddy
    {%- else -%}
      www
    {%- endif -%}
  group: >-
    {%- if use_webserver == "caddy" -%}
      caddy
    {%- else -%}
      www
    {%- endif -%}

system:
  etc: /usr/local/etc
  nginx:
    config_dir: nginx/http.d
  certbot_package: security/py-certbot