---
root:
  user: root
  group: wheel

webserver:
  user: >-
    {%- if use_webserver == "caddy" -%}
      _caddy
    {%- else -%}
      www
    {%- endif -%}
  group: >-
    {%- if use_webserver == "caddy" -%}
      _caddy
    {%- else -%}
      www
    {%- endif -%}

system:
  packages:
    - apache-httpd
    - certbot
  caddy:
    config_dir: /etc/caddy
  nginx:
    config_dir: nginx/http.d
  apache:
    service_name: apache2
    config_dir: /var/www/conf/modules/
    config_file: /etc/apache2/httpd2.conf
    modules:
      - LoadModule rewrite_module /usr/local/lib/apache2/mod_rewrite.so
      - LoadModule ssl_module /usr/local/lib/apache2/mod_ssl.so
      - LoadModule proxy_module /usr/local/lib/apache2/mod_proxy.so
      - LoadModule proxy_http_module /usr/local/lib/apache2/mod_proxy_http.so
      - LoadModule headers_module /usr/local/lib/apache2/mod_headers.so
    modules_disable: []
  certbot:
    config_dir: /etc/letsencrypt