---

webserver:
  user: >-
    {%- if use_webserver == "caddy" -%}
      _caddy
    {%- else -%}
      www
    {%- endif -%}
  group: >-
    {%- if use_webserver == "caddy" -%}
      _caddy
    {%- else -%}
      www
    {%- endif -%}
  error_log: "/var/www/logs/error.log"
  access_log: "/var/www/logs/access.log"
webserver_config:
  apache:
    packages:
      - apache-httpd
      - certbot
    config_file: /etc/apache2/httpd2.conf
    extra_dirs:
      - logs
    modules_config:
      - LoadModule rewrite_module /usr/local/lib/apache2/mod_rewrite.so
      - LoadModule ssl_module /usr/local/lib/apache2/mod_ssl.so
      - LoadModule proxy_module /usr/local/lib/apache2/mod_proxy.so
      - LoadModule proxy_http_module /usr/local/lib/apache2/mod_proxy_http.so
      - LoadModule headers_module /usr/local/lib/apache2/mod_headers.so
      - LoadModule mpm_worker_module /usr/local/lib/apache2/mod_mpm_worker.so
      - LoadModule authz_core_module /usr/local/lib/apache2/mod_authz_core.so
      - LoadModule log_config_module /usr/local/lib/apache2/mod_log_config.so
      - LoadModule unixd_module /usr/local/lib/apache2/mod_unixd.so
      - LoadModule dir_module /usr/local/lib/apache2/mod_dir.so
      - LoadModule mime_module /usr/local/lib/apache2/mod_mime.so
      - LoadModule env_module /usr/local/lib/apache2/mod_env.so
tor:
  directory: /var/tor
