---
root:
  user: root
  group: wheel

webserver:
  user: >-
    {%- if use_webserver == "caddy" -%}
      caddy
    {%- elif use_webserver == "nginx" -%}
      nginx
    {%- elif use_webserver == "apache" -%}
      apache
    {%- else -%}
      www-data
    {%- endif -%}
  group: >-
    {%- if use_webserver == "caddy" -%}
      caddy
    {%- elif use_webserver == "nginx" -%}
      nginx
    {%- elif use_webserver == "apache" -%}
      apache
    {%- else -%}
      www-data
    {%- endif -%}

system:
  packages:
    - httpd
    - certbot
    - mod_ssl
  caddy:
    config_dir: /etc/caddy
  nginx:
    config_dir: nginx/conf.d
  apache:
    service_name: httpd
    config_dir: /etc/httpd/conf.d
    config_file: /etc/httpd/conf/httpd.conf
    modules:
      - LoadModule ssl_module modules/mod_ssl.so
    modules_disable: []
  certbot:
    config_dir: /etc/letsencrypt