---

webserver_config:
  nginx:
    config_dir: /etc/nginx/conf.d
  apache:
    packages:
      - httpd
      - certbot
      - mod_ssl
    service_name: httpd
    server_root: /etc/httpd
    config_dir: /etc/httpd/conf/Includes
    extra_dirs:
      - run
      - conf
    modules_config:
      - Include conf.modules.d/*.conf
