---
root:
  user: root
  group: wheel

webserver:
  user: >-
    {%- if use_webserver == "caddy" -%}
      caddy
    {%- elif use_webserver == "nginx" -%}
      nginx
    {%- elif use_webserver == "apache" -%}
      apache
    {%- else -%}
      www-data
    {%- endif -%}
  group: >-
    {%- if use_webserver == "caddy" -%}
      caddy
    {%- elif use_webserver == "nginx" -%}
      nginx
    {%- elif use_webserver == "apache" -%}
      apache
    {%- else -%}
      www-data
    {%- endif -%}

caddy:
  config_dir: /etc/caddy
nginx:
  config_dir: /etc/nginx/conf.d
apache:
  packages:
    - httpd
    - certbot
    - mod_ssl
  service_name: httpd
  server_root: /etc/httpd
  config_dir: /etc/httpd/conf.d
  config_file: /etc/httpd/conf/httpd.conf
  modules:
    - LoadModule ssl_module modules/mod_ssl.so
certbot:
  config_dir: /etc/letsencrypt