---
root:
  user: root
  group: wheel

webserver:
  user: >-
    {%- if use_webserver == "caddy" -%}
      caddy
    {%- elif use_webserver == "nginx" -%}
      nginx
    {%- else -%}
      www-data
    {%- endif -%}
  group: >-
    {%- if use_webserver == "caddy" -%}
      caddy
    {%- elif use_webserver == "nginx" -%}
      nginx
    {%- else -%}
      www-data
    {%- endif -%}

system:
  caddy:
    config_dir: /etc/caddy
  nginx:
    config_dir: nginx/vhosts.d
  certbot_package: certbot