---
root:
  user: root
  group: wheel

webserver:
  user: >-
    {%- if use_webserver == "caddy" -%}
      caddy
    {%- elif use_webserver == "nginx" -%}
      nginx
    {%- elif use_webserver == "apache" -%}
      wwwrun
    {%- else -%}
      www-data
    {%- endif -%}
  group: >-
    {%- if use_webserver == "caddy" -%}
      caddy
    {%- elif use_webserver == "nginx" -%}
      nginx
    {%- elif use_webserver == "apache" -%}
      wwwrun
    {%- else -%}
      www-data
    {%- endif -%}
  webroot: /var/www/html

system:
  etc: /etc

webserver_config:
  caddy:
    service_name: caddy
    config_dir: /etc/caddy
    extra_dirs: /etc/caddy/configs
  nginx:
    packages:
      - nginx
      - certbot
    service_name: nginx
    config_dir: /etc/nginx/vhosts.d
  apache:
    packages:
      - apache2
      - certbot
      - apache2-utils
    service_name: apache2
    server_root: /etc/apache2
    config_dir: /etc/apache2/Includes
    config_file: /etc/apache2/httpd.conf
    extra_dirs: []
    modules_config:
      - LoadModule rewrite_module /usr/lib64/apache2-prefork/mod_rewrite.so
      - LoadModule ssl_module /usr/lib64/apache2-prefork/mod_ssl.so
      - LoadModule proxy_module /usr/lib64/apache2-prefork/mod_proxy.so
      - LoadModule proxy_http_module /usr/lib64/apache2-prefork/mod_proxy_http.so
      - LoadModule proxy_http2_module /usr/lib64/apache2-prefork/mod_proxy_http2.so
      - LoadModule headers_module /usr/lib64/apache2-prefork/mod_headers.so
      - LoadModule authz_core_module /usr/lib64/apache2-prefork/mod_authz_core.so
      - LoadModule log_config_module /usr/lib64/apache2-prefork/mod_log_config.so
      - LoadModule dir_module /usr/lib64/apache2-prefork/mod_dir.so
      - LoadModule mime_module /usr/lib64/apache2-prefork/mod_mime.so
certbot:
  config_dir: /etc/letsencrypt
  webroot: /var/www/certbot