---

- name: Check if OS-specific vars exist
  ansible.builtin.stat:
    path: "{{ role_path }}/vars/{{ ansible_os_family }}.yaml"
  register: os_vars

- name: Load OS-specific vars
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_distribution }}.yaml'
        - '{{ ansible_os_family }}.yaml'
        - main.yaml
      paths:
        - '{{ role_path }}/vars'
  when: os_vars.stat.exists

- name: Include general
  ansible.builtin.include_tasks: general.yaml

- name: Include ssh
  ansible.builtin.include_tasks: ssh.yaml

- name: Include motd
  ansible.builtin.include_tasks: motd.yaml

- name: Include reboot
  ansible.builtin.include_tasks: reboot.yaml
