---

- name: Generate new motd file
  ansible.builtin.shell:
    cmd: figlet {{ tor.nickname }}{{ item.id }} > /etc/motd
  loop: "{{ servers }}"
  when: inventory_hostname == item.name

- name: Add domain to new motd file
  ansible.builtin.lineinfile:
    path: /etc/motd
    line: "{{ item.domain }}"
  loop: "{{ servers }}"
  when: inventory_hostname == item.name