---

- name: Generate new motd file
  ansible.builtin.shell:
    cmd: figlet {{ tor.nickname }}{{ id }} > /etc/motd

- name: Add domain to new motd file
  ansible.builtin.lineinfile:
    path: /etc/motd
    line: "{{ domain }}"