---

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot if required
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible for package updates"
    reboot_timeout: 300
  when: reboot_required.stat.exists