---

- name: "Configure sshd - disallow root login"
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    create: true
    owner: "{{ root.user }}"
    group: "{{ root.group }}"
    mode: "0644"

- name: "Configure sshd - disable password authentication"
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    create: true
    owner: "{{ root.user }}"
    group: "{{ root.group }}"
    mode: "0644"

- name: "Add admin users"
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups:
      - "{{ root.group }}"
    append: true
    password_lock: false
    shell: "{{ system.shell }}"
  loop: "{{ admins }}"
  loop_control:
    label: "{{ item.name }}"

- name: "Add normal users"
  ansible.builtin.user:
    name: "{{ item.name }}"
    password_lock: false
    shell: "{{ system.shell }}"
  loop: "{{ users }}"
  loop_control:
    label: "{{ item.name }}"

- name: Create .ssh directory for admins
  ansible.builtin.file:
    path: "/home/{{ item.name }}/.ssh"
    state: directory
    owner: "{{ item.name }}"
    mode: 0700
  loop: "{{ admins }}"
  loop_control:
    label: "{{ item.name }}"

- name: Deploy authorized_keys for admins
  ansible.builtin.template:
    src: ./authorized_keys.j2
    dest: "/home/{{ item.name }}/.ssh/authorized_keys"
    owner: "{{ item.name }}"
    mode: 0600
  with_items: "{{ admins }}"

- name: Create .ssh directory for normal users
  ansible.builtin.file:
    path: "/home/{{ item.name }}/.ssh"
    state: directory
    owner: "{{ item.name }}"
    mode: 0700
  loop: "{{ users }}"
  loop_control:
    label: "{{ item.name }}"

- name: Deploy authorized_keys for normal users
  ansible.builtin.template:
    src: ./authorized_keys.j2
    dest: "/home/{{ item.name }}/.ssh/authorized_keys"
    owner: "{{ item.name }}"
    mode: 0600
  with_items: "{{ users }}"

- name: "Add sudoers config for sudo group"
  ansible.builtin.copy:
    content: |
      %{{ root.group }}   ALL=(ALL)   NOPASSWD:ALL
    dest: "{{ system.etc }}/{{ system.sudoers_file }}"
    mode: 0440
