---

- name: "Configure sshd - disallow root login"
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"

- name: "Configure sshd - disable password authentication"
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"

- name: "Add admin users"
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups:
      - "{{ root.group }}"
    append: yes
    shell: "{{ system.shell }}"
  loop: "{{ admins }}"
  loop_control:
    label: "{{ item.name }}"

- name: "Add normal users"
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: "{{ system.shell }}"
  loop: "{{ users }}"
  loop_control:
    label: "{{ item.name }}"

- name: Create .ssh directory
  ansible.builtin.file:
    path: "/home/{{ item.name }}/.ssh"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: "0700"
  loop: "{{ admins }}"
  loop_control:
    label: "{{ item.name }}"

- name: Add SSH public keys for admins
  ansible.builtin.authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1.key }}"
  with_subelements:
    - "{{ admins }}"
    - vars.public-keys

- name: Add SSH public keys for normal users
  ansible.builtin.authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1.key }}"
  with_subelements:
    - "{{ users }}"
    - vars.public-keys

- name: "Add sudoers config for sudo group"
  ansible.builtin.copy:
    content: |
      %sudo   ALL=(ALL)   NOPASSWD:ALL
    dest: /etc/sudoers.d/sudo
    mode: 0440