---

- name: Create SSH-Key
  ansible.builtin.include_tasks: ssh_key.yaml

- name: Create Firewall
  ansible.builtin.include_tasks: firewall.yaml

- name: Create Server
  ansible.builtin.include_tasks: server.yaml