---

- name: Render cloud-init user_data from template
  template:
    src: templates/user_data.j2
    dest: "{{ role_path }}/files/user_data.yaml"
  delegate_to: localhost

- name: Bring Server into defined state
  hetzner.hcloud.server:
    name: "{{ item.name }}"
    server_type: "{{ hcloud.server.type }}"
    image: "{{ hcloud.server.image }}"
    state: "{{ hcloud.server.state }}"
    location: "{{ item.location }}"
    ssh_keys: "{{ hcloud.sshkey[0].name }}"
    firewalls: "{{ hcloud.server.firewalls }}"
    user_data: "{{ lookup('file', 'files/user_data.yaml') }}"
    upgrade_disk: false
    backups: false
    enable_ipv4: "{{ hcloud.server.public_ipv4_enabled }}"
    enable_ipv6: "{{ hcloud.server.public_ipv6_enabled }}"
    delete_protection: false
    rebuild_protection: false
  loop: "{{ servers }}"
  loop_control:
    loop_var: item