---

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true

- name: Restart tor
  ansible.builtin.service:
    name: tor
    state: restarted
    enabled: true