---

- name: Restart tor
  ansible.builtin.service:
    name: tor
    state: restarted
    enabled: true

- name: Restart portacl
  ansible.builtin.service:
    name: portacl
    state: restarted
    enabled: true

- name: Reload daemon
  ansible.builtin.systemd:
    daemon_reload: yes