---

- name: Restart tor
  ansible.builtin.service:
    name: tor
    state: restarted
    enabled: true

- name: Restart caddy
  ansible.builtin.service:
    name: caddy
    state: restarted
    enabled: true