---

- name: Block for creating webtunnel-client
  tags:
    - create-webtunnel-client
  block:
    - name: Get images
      ansible.builtin.shell: vm image list
      register: webtunnel_images

    - name: Set image uuid fact
      ansible.builtin.set_fact:
        webtunnel_image_uuid: "{{ webtunnel_images.stdout_lines | select('search', 'webtunnel-client') | map('regex_replace', '^([^ ]+) .*$', '\\1') | list | first }}"

    - name: Create templated webtunnel-client
      ansible.builtin.shell: vm image provision {{ webtunnel_image_uuid }} {{ os }}-webtunnel-client
      register: provision_result
      failed_when:
        - "'ERROR: new guest already exists' not in provision_result.stderr"
        - provision_result.rc != 0
      changed_when: provision_result.rc == 0

    - name: Render {{ vm[os].template }} template
      ansible.builtin.template:
        src: "{{ role_path }}/templates/webtunnel-client.conf.j2"
        dest: "{{ bhyve.root_dir }}/{{ os }}-webtunnel-client/{{ os }}-webtunnel-client.conf"

    - name: Start {{ vm[os].name }}-webtunnel-client
      ansible.builtin.command: vm start {{ vm[os].name }}-webtunnel-client