---

- name: Block for deleting webtunnel-client
  tags:
    - delete-webtunnel-client
  block:
    - name: Forcefully shutdown {{ vm[os].name }}-webtunnel-client
      shell: vm poweroff -f {{ vm[os].name }}-webtunnel-client
      register: shutdown_webtunnel_client
      failed_when: "'ERROR: {{ vm[os].name }}-{{ item }} doesn't appear to be a running virtual machine' not in shutdown_webtunnel_client.stderr" and shutdown_webtunnel_client.rc != 0

    - name: Wait until VM is stopped
      ansible.builtin.shell: vm list | grep "{{ vm[os].name }}-webtunnel-client" | awk '{print $NF}'
      register: vm_status
      retries: 10
      delay: 3
      until: vm_status.stdout == "Stopped"

    - name: Delete selected vms
      ansible.builtin.shell: vm destroy {{ vm[os].name }}-webtunnel-client