---

- name: Block for deleting VMs
  tags:
    - delete-server
  block:
    - name: Forcefully shutdown {{ vm[os].name }}-{{ webserver_software }}
      ansible.builtin.command: vm poweroff -f {{ vm[os].name }}-{{ item }}
      loop: "{{ webserver_software }}"
      failed_when: false

    - name: Wait until VM is stopped
      ansible.builtin.shell: |
        set -o pipefail
        vm list | grep "{{ vm[os].name }}-{{ item }}" | awk '{print $NF}'
      register: vm_status
      retries: 10
      delay: 3
      until: vm_status.stdout == "Stopped"
      loop: "{{ webserver_software }}"

    - name: Delete selected vms
      ansible.builtin.command: vm destroy {{ vm[os].name }}-{{ item }}
      loop: "{{ webserver_software }}"
