---

- name: Block for deleting webtunnel-client
  tags:
    - delete-webtunnel-client
  block:
    - name: Forcefully shutdown {{ vm[os].name }}-webtunnel-client
      ansible.builtin.command: vm poweroff -f {{ vm[os].name }}-webtunnel-client
      failed_when: false
      changed_when: true # Idempotently changes every time. Set just for ansible-lint.

    - name: Wait until VM is stopped
      ansible.builtin.shell: |
        set -o pipefail
        vm list | grep "{{ vm[os].name }}-webtunnel-client" | awk '{print $NF}'
      register: vm_status
      retries: 10
      delay: 3
      until: vm_status.stdout == "Stopped"
      changed_when: false # No changes will be applied. Set just for ansible-lint.
      failed_when: 
        - vm_status.rc != 0
        - "'' not in vm_status.stdout"

    - name: Delete selected vms
      ansible.builtin.command: vm destroy {{ vm[os].name }}-webtunnel-client
      changed_when: true # Idempotently changes every time. Set just for ansible-lint.
