---

- name: Block for deleting webtunnel-client
  tags:
    - delete-webtunnel-client
  block:
    - name: Delete selected vms
      ansible.builtin.shell: vm destroy {{ vm[os].name }}-webtunnel-client