---

- name: Include create provisioned server
  ansible.builtin.include_tasks: create-os-provision.yaml
  tags:
    - create-server

- name: Include delete provisioned server
  ansible.builtin.include_tasks: delete-os-provision.yaml
  tags:
    - delete-server

- name: Include shutdown provisioned server 
  ansible.builtin.include_tasks: shutdown-os-provision.yaml
  tags:
    - shutdown-server

- name: Include starting all vms
  ansible.builtin.include_tasks: start-vms.yaml
  tags:
    - start-server

- name: Include create wetunnel-client
  ansible.builtin.include_tasks: create-webtunnel-client.yaml
  tags:
    - create-webtunnel-client

- name: Include delete webtunnel-client
  ansible.builtin.include_tasks: delete-webtunnel-client.yaml
  tags:
    - delete-webtunnel-client