- name: Block for shutting down VMs
  tags:
    - shutdown-server
  block:
    - name: Forcefully shutdown {{ vm[os].name }}-{{ webserver_software }}
      shell: vm poweroff -f {{ vm[os].name }}-{{ item }}
      loop: "{{ webserver_software }}"
      failed_when: false