---

- name: Block for starting all VMs
  tags:
    - start-server
  block:
    - name: Start VMs
      ansible.builtin.command: vm start {{ os }}-{{ item }}
      loop: "{{ webserver_software }}"
      changed_when: true # Idempotently changes every time. Set just for ansible-lint.
