---

- name: Include nginx
  ansible.builtin.include_tasks: nginx.yaml
  tags:
    - nginx
    - certbot
    - certificate
    
- name: Include webtunnel
  ansible.builtin.include_tasks: webtunnel.yaml