---

- name: Block for requesting a certificate and setting up nginx
  tags:
    - nginx
    - certbot
    - certificate
  block:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - nginx
          - certbot
        state: present
        update_cache: true

    - name: Create webroot for Certbot
      ansible.builtin.file:
        path: /var/www/certbot
        state: directory
        owner: root
        group: root

    - name: Copy http.conf
      ansible.builtin.copy:
        src: "{{ role_path }}/files/http.conf"
        dest: /etc/nginx/sites-available/http.conf
        owner: root
        group: root

    - name: Link http.conf to sites-enabled
      ansible.builtin.file:
        src: /etc/nginx/sites-available/http.conf
        dest: /etc/nginx/sites-enabled/http.conf
        state: link

    - name: Remove nginx default site
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Restart webserver
      ansible.builtin.service:
        name: nginx
        state: restarted

    - name: Request certificates
      ansible.builtin.shell: |
        certbot certonly --agree-tos --email {{ email }} --non-interactive --webroot -w /var/www/certbot -d {{ domain }} --cert-name {{ domain }}

    - name: Create cron job for certbot renewal
      cron:
        name: "Renew Let's Encrypt SSL certificate"
        minute: "0"
        hour: "3"
        day: "*"
        month: "*"
        weekday: "*"
        job: "/usr/bin/certbot renew"
        state: present

    - name: Generate random string with 24 characters
      ansible.builtin.shell: echo $(cat /dev/urandom | tr -cd "qwertyuiopasdfghjklzxcvbnmMNBVCXZLKJHGFDSAQWERTUIOP0987654321"|head -c 24)
      register: random_string

    - name: Check, if https.conf exists
      ansible.builtin.stat:
        path: /etc/nginx/sites-available/https.conf
      register: https_conf

    - name: Template https.conf
      ansible.builtin.template:
        src: "{{ role_path }}/templates/https.conf.j2"
        dest: /etc/nginx/sites-available/https.conf
        owner: root
        group: root

    - name: Link https.conf to sites-enabled
      ansible.builtin.file:
        src: /etc/nginx/sites-available/https.conf
        dest: /etc/nginx/sites-enabled/https.conf
        state: link
      notify: Restart nginx