---

- name: Block for getting random string
  tags:
    - random
    - string
    - random-string
  block:
    - name: Generate random string with 24 characters
      ansible.builtin.set_fact:
        random_string: "{{ lookup('community.general.random_string', length=24, special=False) }}"

    - name: Check if random string exists
      ansible.builtin.stat:
        path: "{{ tor.directory }}/random-string.txt"
      register: random_string_file

    - name: Create files with the random strings
      ansible.builtin.lineinfile:
        path: "{{ tor.directory }}/random-string.txt"
        line: "{{ random_string }}"
        owner: "{{ root.user }}"
        group: "{{ root.group }}"
        mode: 0500
        create: true
      when: not random_string_file.stat.exists
