---

- name: Block for getting random string
  tags:
    - random
    - string
    - random-string
  block:
    - name: Generate random string with 24 characters
      ansible.builtin.shell: echo $(cat /dev/urandom | tr -cd "qwertyuiopasdfghjklzxcvbnmMNBVCXZLKJHGFDSAQWERTUIOP0987654321"|head -c 24)
      register: random_string
      delegate_to: localhost
      become: false

    - name: Check if random string exists
      ansible.builtin.stat:
        path: "{{ tor.directory }}/random-string.txt"
      register: random_string_file

    - name: Create files with the random strings
      ansible.builtin.lineinfile:
        path: "{{ tor.directory }}/random-string.txt"
        line: "{{ random_string.stdout }}"
        owner: "{{ root.user }}"
        group: "{{ root.group }}"
        mode: 0500
        create: true
      when: not random_string_file.stat.exists