---
- name: Block for setting up the webroot
  when: not reverse_proxy
  block:
    - name: Create /var/www folder
      ansible.builtin.file:
        path: /var/www
        state: directory
        owner: root
        group: root
    
    - name: Create /var/www/html folder
      ansible.builtin.file:
        path: "{{ dir.webroot }}"
        state: directory
        owner: caddy
        group: caddy
    
    - name: Copy index.html
      ansible.builtin.copy:
        src: "{{ role_path }}/files/index.html"
        dest: "{{ dir.webroot }}"
        owner: caddy
        group: caddy
      notify: Reload caddy
    
    - name: Copy bear.svg
      ansible.builtin.copy:
        src: "{{ role_path }}/files/bear.svg"
        dest: "{{ dir.webroot }}"
        owner: caddy
        group: caddy
      notify: Reload caddy