- name: Restart ssh
  service:
    name: ssh
    state: restarted
    enabled: true

- name: Restart crond
  ansible.builtin.service:
    name: crond
    state: restarted
    enabled: true

- name: Restart dnf-automatic
  ansible.builtin.service:
    name: dnf-automatic.timer
    state: restarted
    enabled: true

- name: Restart system
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible for setting the hostname"
    pre_reboot_delay: 10
    post_reboot_delay: 10
    reboot_timeout: 60