- name: Restart ssh
  service:
    name: ssh
    state: restarted
    enabled: true

- name: Restart crond
  ansible.builtin.service:
    name: crond
    state: restarted
    enabled: true

- name: Restart dnf-automatic
  ansible.builtin.service:
    name: dnf-automatic.timer
    state: restarted
    enabled: true