---

- name: Get docker setup script
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: /tmp/docker-setup.sh
    mode: "0700"
    owner: "{{ root.user }}"
    group: "{{ root.group }}"

- name: Run install script
  ansible.builtin.script:
    cmd: /tmp/docker-setup.sh
  notify: Start docker
