---

- name: Create LetsEncrypt certificate renewal cronjob
  ansible.builtin.cron:
    name: "Renew Certbot Certificate"
    minute: "0"
    hour: "12"
    weekday: "7"
    user: root
    job: "docker compose -f {{ docker.directory }}/docker-compose.yml -rm certbot renew"

- name: Create filestructure in {{ docker.directory }}
  ansible.builtin.file:
    path: "{{ docker.directory }}/{{ item }}"
    state: directory
    mode: "0775"
    owner: "{{ root.user }}"
    group: docker
  loop:
    - files
    - files/certbot
    - files/certbot/www
    - files/certbot/conf

- name: Get the connection strings for testing in Tor Browser
  ansible.builtin.command:
    cmd: docker compose exec -f {{ docker.directory }}/docker-compose.yml webtunnel-bridge get-bridge-line.sh
  changed_when: false # No changes will be applied. Set just for ansible-lint.
  register: connection_string

- name: Write connection strings to a file
  ansible.builtin.lineinfile:
    path: "{{ role_path }}/../../connection-strings.txt"
    line: "{{ item }} #{{ inventory_hostname }}"
    create: true
    mode: "0644"
  with_items: "{{ connection_string.stdout_lines }}"
  delegate_to: localhost
  become: false
