---

- name: Block for certificate request
  block:
    - name: Test certificate request
      ansible.builtin.shell: |
        certbot certonly --webroot -w {{ webserver.webroot }} --cert-name {{ domain }} -d {{ domain }} --non-interactive --email {{ email }} --agree-tos --config-dir {{ certbot.config_dir }} --dry-run
      register: certbot_test_output
      failed_when: "'Some challenges have failed.' in certbot_test_output.stderr"
      changed_when: "'The dry run was successful.' in certbot_test_output.stdout"

    - name: Request certificate
      ansible.builtin.shell: |
        certbot certonly --webroot -w {{ webserver.webroot }} --cert-name {{ domain }} -d {{ domain }} --non-interactive --email {{ email }} --agree-tos --config-dir {{ certbot.config_dir }}
      register: certbot_output
      changed_when: "'Certificate not yet due for renewal' not in certbot_output.stdout"
