---

- name: Create log directory
  ansible.builtin.file:
    path: /var/log/{{ webserver_config[use_webserver].service_name }}
    state: "directory"
    owner: "{{ root.user }}"
    group: "{{ root.group }}"
    mode: "0700"

- name: Create caddy (error) logfile
  ansible.builtin.file:
    path: "/var/log/{{ webserver_config[use_webserver].service_name }}/error.log"
    state: "touch"
    owner: "{{ root.user }}"
    group: "{{ root.group }}"
    mode: "0644"
