---

- name: Block for OS-specific (RedHat)
  when: ansible_os_family == "RedHat"
  block:
    - name: Ensure SELinux file context for Caddy log directory
      community.general.sefcontext:
        target: "/var/log/caddy(/.*)?"
        setype: httpd_log_t
        state: present

    - name: Apply SELinux context to /var/log/caddy
      ansible.builtin.command: restorecon -Rv /var/log/caddy
      register: caddy_selinux
      changed_when: "'' not in caddy_selinux.stdout"

- name: Ensure log directory for caddy exists
  ansible.builtin.file:
    path: "{{ webserver.error_log | dirname }}"
    state: directory
    owner: "{{ webserver.user }}"
    group: "{{ webserver.group }}"
    mode: "0644"

- name: Set permissions to (error) logfile
  ansible.builtin.file:
    path: "{{ webserver.error_log }}"
    state: touch
    owner: "{{ webserver.user }}"
    group: "{{ webserver.group }}"
    mode: "0644"
