---

- name: Install Logrotate
  ansible.builtin.package:
    name: logrotate
    state: present

- name: Create logrotate configuration
  ansible.builtin.template:
    src: "{{ role_path }}/templates/logrotate.j2"
    dest: "{{ system.etc }}/logrotate.d/{{ use_webserver }}"
    owner: "{{ root.user }}"
    group: "{{ root.group }}"
    mode: "0644"

- name: Test logrotate
  ansible.builtin.command:
    cmd: logrotate {{ system.etc }}/logrotate.conf
  changed_when: false
  register: logrotate
  failed_when:
    - logrotate.rc != 0
    - "'already exists, skipping rotation' not in logrotate.stderr"

- name: Add crontab entry for logrotate
  ansible.builtin.cron:
    name: Logrotate
    job: logrotate {{ system.etc }}/logrotate.conf
    hour: 0
    minute: 0
    user: root
