---
- name: Block for setting up the webroot
  when: not reverse_proxy and deploy_webroot
  block:
    - name: Create /var/www folder
      ansible.builtin.file:
        path: /var/www
        state: directory
        owner: "{{ root.user }}"
        group: "{{ root.group }}"
        mode: "0755"

    - name: Create /var/www/html folder
      ansible.builtin.file:
        path: "{{ webserver.webroot }}"
        state: directory
        owner: "{{ webserver.user }}"
        group: "{{ webserver.group }}"
        mode: "0755"

    - name: Copy index.html
      ansible.builtin.copy:
        src: "{{ role_path }}/files/index.html"
        dest: "{{ webserver.webroot }}"
        owner: "{{ webserver.user }}"
        group: "{{ webserver.group }}"
        mode: "0644"
      notify: Validate {{ use_webserver }}

    - name: Copy bear.svg
      ansible.builtin.copy:
        src: "{{ role_path }}/files/bear.svg"
        dest: "{{ webserver.webroot }}"
        owner: "{{ webserver.user }}"
        group: "{{ webserver.group }}"
        mode: "0644"
      notify: Validate {{ use_webserver }}

    - name: Copy robots.txt
      ansible.builtin.copy:
        src: "{{ role_path }}/files/robots.txt"
        dest: "{{ webserver.webroot }}"
        owner: "{{ webserver.user }}"
        group: "{{ webserver.group }}"
        mode: "0644"
      notify: Validate {{ use_webserver }}
      when: website.no_index
