---

hcloud:
  firewalls:
    - name: firewall-default
      state: present
      rules:
        - description: ssh
          direction: in
          protocol: tcp
          port: 22
          source_ips:
            - 0.0.0.0/0
            - ::/0
        - description: icmp
          direction: in
          protocol: icmp
          source_ips:
            - 0.0.0.0/0
            - ::/0
        - description: tcp
          direction: out
          protocol: tcp
          port: any
          destination_ips:
            - 0.0.0.0/0
            - ::/0
        - description: udp
          direction: out
          protocol: udp
          port: any
          destination_ips:
            - 0.0.0.0/0
            - ::/0
        - description: icmp
          direction: out
          protocol: icmp
          destination_ips:
            - 0.0.0.0/0
            - ::/0
    - name: firewall-web
      state: present
      rules:
        - description: http
          direction: in
          protocol: tcp
          port: 80
          source_ips:
            - 0.0.0.0/0
            - ::/0
        - description: https
          direction: in
          protocol: tcp
          port: 443
          source_ips:
            - 0.0.0.0/0
            - ::/0
  server:
    state: present
    image: ubuntu-24.04
    backup: false
    public_ipv6_enabled: true
    public_ipv4_enabled: true
    firewalls:
      - firewall-default
      - firewall-web
    volumes: []
  servers:
    - name: bridge-nbg-0
      location: nbg1
      image: ubuntu-24.04
      type: cax11
    - name: bridge-fsn-0
      location: fsn1
      image: ubuntu-24.04
      type: cax11
    - name: bridge-hel-0
      location: hel1
      image: ubuntu-24.04
      type: cax11
    - name: bridge-hel-1
      location: hel1
      image: ubuntu-24.04
      type: cax11
