---

name: Create host vars of test hosts

on:
  schedule:
    - cron: '0 0 */3 * *'
  push:
    branches-ignore:
      - main
    paths:
      - '.github/workflows/hostvars.yml'
      - 'scripts/generate_host_vars.py'
  workflow_dispatch:

env:
  ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
  PY_COLORS: 1
  ANSIBLE_FORCE_COLOR: 1

jobs:
  generate-host-vars:
    runs-on: self-hosted
    env:
      TEST_SERVER_TLD: ${{ secrets.TEST_SERVER_TLD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download venv
        shell: bash
        run: |
          rsync -avz --no-o --no-g --delete 10.1.0.100:venv . >/dev/null && \
          echo "Downloaded venv successfully."

      - name: Generate host_vars/os-webserver.yaml
        run: |
          source venv/bin/activate
          python3 scripts/generate_host_vars.py

      - name: Upload test_host_vars to S3
        shell: bash
        run: |
          rsync -avz --no-o --no-g --delete test_host_vars 10.1.0.100: >/dev/null && \
          echo "Uploaded test_host_vars successfully."
