---

name: Test Ansible Playbook

on:
  schedule:
    - cron: '0 0 */3 * *'
  push:
    branches-ignore:
      - main
    paths:
      - '.github/workflows/hostvars.yml'
      - 'scripts/generate_host_vars.py'

env:
  ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
  PY_COLORS: 1
  ANSIBLE_FORCE_COLOR: 1

jobs:
  generate-host-vars:
    runs-on: self-hosted
    env:
      TEST_SERVER_TLD: ${{ secrets.TEST_SERVER_TLD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to S3
        uses: mc-actions/configure@v1
        with:
          s3_server: '${{ secrets.S3_ENDPOINT }}'
          s3_access_key: '${{ secrets.S3_ACCESS_KEY }}'
          s3_secret_key: '${{ secrets.S3_SECRET_KEY }}'

      - name: Download venv from S3
        shell: bash
        run: |
          mc cp -r default/actions-artifacts/venv/ venv/ >/dev/null && \
          echo "Downloaded venv successfully. Changing permissions now."
          chmod +x venv/bin/*

      - name: Generate host_vars/os-webserver.yaml
        run: |
          source venv/bin/activate
          python3 scripts/generate_host_vars.py

      - name: Upload test_host_vars to S3
        shell: bash
        run: |
          mc cp -r test_host_vars/ default/actions-artifacts/test_host_vars/ >/dev/null && \
          echo "Uploaded test_host_vars successfully."