name: Test Ansible Playbook by Server

on:
  push:
    branches-ignore:
      - main

jobs:
  setup-ubuntu:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ubuntu servers
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          ansible-playbook actions-playbook.yaml --tags=create-server -i actions-inventory.ini -e "os=ubuntu"

      - name: Wait until the hosts are reacheable
        run: |
          python3 scripts/check_hosts.py --limit ubuntu -i actions-inventory.ini

      - name: Run Ansible Playbook Test for Ubuntu
        run: |
          chmod +x ansible-playbook.sh
          ansible-playbook playbook.yaml --limit=ubuntu -i actions-inventory.ini

  test-ubuntu:
    needs: 
      - setup-ubuntu
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Test connections
        run: |
          chmod +x scripts/test-connection.sh
          ./test-connection.sh

      - name: Shutdown ubuntu servers
        run: |
          chmod +x ansible-playbook.sh
          ansible-playbook playbook.yaml --tags=shutdown-server --limit=ubuntu -i actions-inventory.ini

      - name: Destroy ubuntu servers
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          chmod +x ansible-playbook.sh
          ansible-playbook actions-playbook.yaml --tags=delete-server -i actions-inventory.ini -e "os=ubuntu"
        if: success()
