name: Test Ansible Playbook by Server

on:
  push:
    branches-ignore:
      - main

jobs:
  setup-ubuntu:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ubuntu servers
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=create-server -i actions-inventory.ini -e "os=ubuntu"

      - name: Wait until the ubuntu servers are reacheable
        run: |
          python3 scripts/check_hosts.py --limit ubuntu -i actions-inventory.ini

      - name: Run Ansible Playbook Test for Ubuntu
        run: |
          ./ansible-playbook.sh playbook.yaml --limit=ubuntu -i actions-inventory.ini

      - name: Upload connection-strings
        uses: actions/upload-artifact@v4
        with:
          name: connection-strings-ubuntu
          path: connection-strings.txt

  test-ubuntu:
    needs: 
      - setup-ubuntu
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ubuntu webtunnel-client
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=create-webtunnel-client -i actions-inventory.ini -e "os=ubuntu"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: connection-strings-ubuntu

      - name: Check webtunnel-client availablity
        run: |
          ./scripts/check_client_availability.sh

      - name: Test connections
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=test-webtunnel --limit=ubuntu-webtunnel-client -i actions-inventory.ini 

      - name: Shutdown ubuntu servers
        run: |
          ./ansible-playbook.sh playbook.yaml --tags=shutdown-server --limit=ubuntu -i actions-inventory.ini

      - name: Delete ubuntu webtunnel-client
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=delete-webtunnel-client -i actions-inventory.ini -e "os=ubuntu"

  setup-alpine:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create alpine servers
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=create-server -i actions-inventory.ini -e "os=alpine"

      - name: Wait until the alpine servers are reacheable
        run: |
          python3 scripts/check_hosts.py --limit alpine -i actions-inventory.ini

      - name: Run Ansible Playbook Test for alpine
        run: |
          ./ansible-playbook.sh playbook.yaml --limit=alpine -i actions-inventory.ini

      - name: Upload connection-strings
        uses: actions/upload-artifact@v4
        with:
          name: connection-strings-alpine
          path: connection-strings.txt

  test-alpine:
    needs: 
      - setup-alpine
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create alpine webtunnel-client
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=create-webtunnel-client -i actions-inventory.ini -e "os=alpine"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: connection-strings-alpine

      - name: Check webtunnel-client availablity
        run: |
          ./scripts/check_client_availability.sh

      - name: Test connections
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=test-webtunnel --limit=alpine-webtunnel-client -i actions-inventory.ini 

      - name: Shutdown alpine servers
        run: |
          ./ansible-playbook.sh playbook.yaml --tags=shutdown-server --limit=alpine -i actions-inventory.ini

      - name: Delete alpine webtunnel-client
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=delete-webtunnel-client -i actions-inventory.ini -e "os=alpine"

  setup-archlinux:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create archlinux servers
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=create-server -i actions-inventory.ini -e "os=archlinux"

      - name: Wait until the archlinux servers are reacheable
        run: |
          python3 scripts/check_hosts.py --limit archlinux -i actions-inventory.ini

      - name: Run Ansible Playbook Test for archlinux
        run: |
          ./ansible-playbook.sh playbook.yaml --limit=archlinux -i actions-inventory.ini

      - name: Upload connection-strings
        uses: actions/upload-artifact@v4
        with:
          name: connection-strings-archlinux
          path: connection-strings.txt

  test-archlinux:
    needs: 
      - setup-archlinux
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create archlinux webtunnel-client
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=create-webtunnel-client -i actions-inventory.ini -e "os=archlinux"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: connection-strings-archlinux

      - name: Check webtunnel-client availablity
        run: |
          ./scripts/check_client_availability.sh

      - name: Test connections
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=test-webtunnel --limit=archlinux-webtunnel-client -i actions-inventory.ini 

      - name: Shutdown archlinux servers
        run: |
          ./ansible-playbook.sh playbook.yaml --tags=shutdown-server --limit=archlinux -i actions-inventory.ini

      - name: Delete archlinux webtunnel-client
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=delete-webtunnel-client -i actions-inventory.ini -e "os=archlinux"

  setup-freebsd:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create freebsd servers
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=create-server -i actions-inventory.ini -e "os=freebsd"

      - name: Wait until the freebsd servers are reacheable
        run: |
          python3 scripts/check_hosts.py --limit freebsd -i actions-inventory.ini

      - name: Run Ansible Playbook Test for freebsd
        run: |
          ./ansible-playbook.sh playbook.yaml --limit=freebsd -i actions-inventory.ini

      - name: Upload connection-strings
        uses: actions/upload-artifact@v4
        with:
          name: connection-strings-freebsd
          path: connection-strings.txt

  test-freebsd:
    needs: 
      - setup-freebsd
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create freebsd webtunnel-client
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=create-webtunnel-client -i actions-inventory.ini -e "os=freebsd"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: connection-strings-freebsd

      - name: Check webtunnel-client availablity
        run: |
          ./scripts/check_client_availability.sh

      - name: Test connections
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=test-webtunnel --limit=freebsd-webtunnel-client -i actions-inventory.ini 

      - name: Shutdown freebsd servers
        run: |
          ./ansible-playbook.sh playbook.yaml --tags=shutdown-server --limit=freebsd -i actions-inventory.ini

      - name: Delete freebsd webtunnel-client
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=delete-webtunnel-client -i actions-inventory.ini -e "os=freebsd"

  setup-openbsd:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create openbsd servers
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=create-server -i actions-inventory.ini -e "os=openbsd"

      - name: Wait until the openbsd servers are reacheable
        run: |
          python3 scripts/check_hosts.py --limit openbsd -i actions-inventory.ini

      - name: Run Ansible Playbook Test for openbsd
        run: |
          ./ansible-playbook.sh playbook.yaml --limit=openbsd -i actions-inventory.ini

      - name: Upload connection-strings
        uses: actions/upload-artifact@v4
        with:
          name: connection-strings-openbsd
          path: connection-strings.txt

  test-openbsd:
    needs: 
      - setup-openbsd
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create openbsd webtunnel-client
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=create-webtunnel-client -i actions-inventory.ini -e "os=openbsd"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: connection-strings-openbsd

      - name: Check webtunnel-client availablity
        run: |
          ./scripts/check_client_availability.sh

      - name: Test connections
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=test-webtunnel --limit=openbsd-webtunnel-client -i actions-inventory.ini 

      - name: Shutdown openbsd servers
        run: |
          ./ansible-playbook.sh playbook.yaml --tags=shutdown-server --limit=openbsd -i actions-inventory.ini

      - name: Delete openbsd webtunnel-client
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=delete-webtunnel-client -i actions-inventory.ini -e "os=openbsd"

  setup-rhel:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create rhel servers
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=create-server -i actions-inventory.ini -e "os=rhel"

      - name: Wait until the rhel servers are reacheable
        run: |
          python3 scripts/check_hosts.py --limit rhel -i actions-inventory.ini

      - name: Run Ansible Playbook Test for rhel
        run: |
          ./ansible-playbook.sh playbook.yaml --limit=rhel -i actions-inventory.ini

      - name: Upload connection-strings
        uses: actions/upload-artifact@v4
        with:
          name: connection-strings-rhel
          path: connection-strings.txt

  test-rhel:
    needs: 
      - setup-rhel
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create rhel webtunnel-client
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=create-webtunnel-client -i actions-inventory.ini -e "os=rhel"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: connection-strings-rhel

      - name: Check webtunnel-client availablity
        run: |
          ./scripts/check_client_availability.sh

      - name: Test connections
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=test-webtunnel --limit=rhel-webtunnel-client -i actions-inventory.ini 

      - name: Shutdown rhel servers
        run: |
          ./ansible-playbook.sh playbook.yaml --tags=shutdown-server --limit=rhel -i actions-inventory.ini

      - name: Delete rhel webtunnel-client
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=delete-webtunnel-client -i actions-inventory.ini -e "os=rhel"

  setup-suse:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create suse servers
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=create-server -i actions-inventory.ini -e "os=suse"

      - name: Wait until the suse servers are reacheable
        run: |
          python3 scripts/check_hosts.py --limit suse -i actions-inventory.ini

      - name: Run Ansible Playbook Test for suse
        run: |
          ./ansible-playbook.sh playbook.yaml --limit=suse -i actions-inventory.ini

      - name: Upload connection-strings
        uses: actions/upload-artifact@v4
        with:
          name: connection-strings-suse
          path: connection-strings.txt

  test-suse:
    needs: 
      - setup-suse
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create suse webtunnel-client
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=create-webtunnel-client -i actions-inventory.ini -e "os=suse"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: connection-strings-suse

      - name: Check webtunnel-client availablity
        run: |
          ./scripts/check_client_availability.sh

      - name: Test connections
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=test-webtunnel --limit=suse-webtunnel-client -i actions-inventory.ini 

      - name: Shutdown suse servers
        run: |
          ./ansible-playbook.sh playbook.yaml --tags=shutdown-server --limit=suse -i actions-inventory.ini

      - name: Delete suse webtunnel-client
        env:
          ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=delete-webtunnel-client -i actions-inventory.ini -e "os=suse"