name: Test Ansible Playbook by Server

on:
  push:
    branches-ignore:
      - main

env:
  ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}

jobs:
  setup-ubuntu:
    runs-on: self-hosted
    env:
      OS: ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ${{ env.OS }} servers
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=create-server -i actions-inventory.ini -e "os=${{ env.OS }}"

      - name: Wait until the ${{ env.OS }} servers are reachable
        run: |
          python3 scripts/check_hosts.py --limit ${{ env.OS }} -i actions-inventory.ini

      - name: Run Ansible Playbook Test for ${{ env.OS }}
        run: |
          ./ansible-playbook.sh playbook.yaml --limit=${{ env.OS }} -i actions-inventory.ini

      - name: Upload connection-strings for ${{ env.OS }}
        uses: actions/upload-artifact@v4
        with:
          name: connection-strings-${{ env.OS }}
          path: connection-strings.txt

  test-ubuntu:
    needs: 
      - setup-ubuntu
    runs-on: self-hosted
    env:
      OS: ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ${{ env.OS }} webtunnel-client
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=create-webtunnel-client -i actions-inventory.ini -e "os=${{ env.OS }}"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: connection-strings-${{ env.OS }}

      - name: Wait until the ${{ env.OS }} servers are reacheable
        run: |
          python3 scripts/check_hosts.py --limit=${{ env.OS }}-webtunnel-client -i actions-inventory.ini

      - name: Test connections
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=test-webtunnel --limit=${{ env.OS }}-webtunnel-client -i actions-inventory.ini 

      - name: Shutdown ${{ env.OS }} servers
        run: |
          ./ansible-playbook.sh playbook.yaml --tags=shutdown-server --limit=${{ env.OS }} -i actions-inventory.ini

      - name: Delete ${{ env.OS }} webtunnel-client
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=delete-webtunnel-client -i actions-inventory.ini -e "os=${{ env.OS }}"

  setup-alpine:
    runs-on: self-hosted
    env:
      OS: alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ${{ env.OS }} servers
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=create-server -i actions-inventory.ini -e "os=${{ env.OS }}"

      - name: Wait until the ${{ env.OS }} servers are reachable
        run: |
          python3 scripts/check_hosts.py --limit ${{ env.OS }} -i actions-inventory.ini

      - name: Run Ansible Playbook Test for ${{ env.OS }}
        run: |
          ./ansible-playbook.sh playbook.yaml --limit=${{ env.OS }} -i actions-inventory.ini

      - name: Upload connection-strings for ${{ env.OS }}
        uses: actions/upload-artifact@v4
        with:
          name: connection-strings-${{ env.OS }}
          path: connection-strings.txt

  test-alpine:
    needs: 
      - setup-alpine
    runs-on: self-hosted
    env:
      OS: alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ${{ env.OS }} webtunnel-client
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=create-webtunnel-client -i actions-inventory.ini -e "os=${{ env.OS }}"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: connection-strings-${{ env.OS }}

      - name: Wait until the ${{ env.OS }} servers are reacheable
        run: |
          python3 scripts/check_hosts.py --limit=${{ env.OS }}-webtunnel-client -i actions-inventory.ini

      - name: Test connections
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=test-webtunnel --limit=${{ env.OS }}-webtunnel-client -i actions-inventory.ini 

      - name: Shutdown ${{ env.OS }} servers
        run: |
          ./ansible-playbook.sh playbook.yaml --tags=shutdown-server --limit=${{ env.OS }} -i actions-inventory.ini

      - name: Delete ${{ env.OS }} webtunnel-client
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=delete-webtunnel-client -i actions-inventory.ini -e "os=${{ env.OS }}"

  setup-archlinux:
    runs-on: self-hosted
    env:
      OS: archlinux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ${{ env.OS }} servers
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=create-server -i actions-inventory.ini -e "os=${{ env.OS }}"

      - name: Wait until the ${{ env.OS }} servers are reachable
        run: |
          python3 scripts/check_hosts.py --limit ${{ env.OS }} -i actions-inventory.ini

      - name: Run Ansible Playbook Test for ${{ env.OS }}
        run: |
          ./ansible-playbook.sh playbook.yaml --limit=${{ env.OS }} -i actions-inventory.ini

      - name: Upload connection-strings for ${{ env.OS }}
        uses: actions/upload-artifact@v4
        with:
          name: connection-strings-${{ env.OS }}
          path: connection-strings.txt

  test-archlinux:
    needs: 
      - setup-archlinux
    runs-on: self-hosted
    env:
      OS: archlinux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ${{ env.OS }} webtunnel-client
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=create-webtunnel-client -i actions-inventory.ini -e "os=${{ env.OS }}"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: connection-strings-${{ env.OS }}

      - name: Wait until the ${{ env.OS }} servers are reacheable
        run: |
          python3 scripts/check_hosts.py --limit=${{ env.OS }}-webtunnel-client -i actions-inventory.ini

      - name: Test connections
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=test-webtunnel --limit=${{ env.OS }}-webtunnel-client -i actions-inventory.ini 

      - name: Shutdown ${{ env.OS }} servers
        run: |
          ./ansible-playbook.sh playbook.yaml --tags=shutdown-server --limit=${{ env.OS }} -i actions-inventory.ini

      - name: Delete ${{ env.OS }} webtunnel-client
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=delete-webtunnel-client -i actions-inventory.ini -e "os=${{ env.OS }}"

  setup-freebsd:
    runs-on: self-hosted
    env:
      OS: freebsd
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ${{ env.OS }} servers
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=create-server -i actions-inventory.ini -e "os=${{ env.OS }}"

      - name: Wait until the ${{ env.OS }} servers are reachable
        run: |
          python3 scripts/check_hosts.py --limit ${{ env.OS }} -i actions-inventory.ini

      - name: Run Ansible Playbook Test for ${{ env.OS }}
        run: |
          ./ansible-playbook.sh playbook.yaml --limit=${{ env.OS }} -i actions-inventory.ini

      - name: Upload connection-strings for ${{ env.OS }}
        uses: actions/upload-artifact@v4
        with:
          name: connection-strings-${{ env.OS }}
          path: connection-strings.txt

  test-freebsd:
    needs: 
      - setup-freebsd
    runs-on: self-hosted
    env:
      OS: freebsd
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ${{ env.OS }} webtunnel-client
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=create-webtunnel-client -i actions-inventory.ini -e "os=${{ env.OS }}"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: connection-strings-${{ env.OS }}

      - name: Wait until the ${{ env.OS }} servers are reacheable
        run: |
          python3 scripts/check_hosts.py --limit=${{ env.OS }}-webtunnel-client -i actions-inventory.ini

      - name: Test connections
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=test-webtunnel --limit=${{ env.OS }}-webtunnel-client -i actions-inventory.ini 

      - name: Shutdown ${{ env.OS }} servers
        run: |
          ./ansible-playbook.sh playbook.yaml --tags=shutdown-server --limit=${{ env.OS }} -i actions-inventory.ini

      - name: Delete ${{ env.OS }} webtunnel-client
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=delete-webtunnel-client -i actions-inventory.ini -e "os=${{ env.OS }}"

  setup-openbsd:
    runs-on: self-hosted
    env:
      OS: openbsd
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ${{ env.OS }} servers
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=create-server -i actions-inventory.ini -e "os=${{ env.OS }}"

      - name: Wait until the ${{ env.OS }} servers are reachable
        run: |
          python3 scripts/check_hosts.py --limit ${{ env.OS }} -i actions-inventory.ini

      - name: Run Ansible Playbook Test for ${{ env.OS }}
        run: |
          ./ansible-playbook.sh playbook.yaml --limit=${{ env.OS }} -i actions-inventory.ini

      - name: Upload connection-strings for ${{ env.OS }}
        uses: actions/upload-artifact@v4
        with:
          name: connection-strings-${{ env.OS }}
          path: connection-strings.txt

  test-openbsd:
    needs: 
      - setup-openbsd
    runs-on: self-hosted
    env:
      OS: openbsd
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ${{ env.OS }} webtunnel-client
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=create-webtunnel-client -i actions-inventory.ini -e "os=${{ env.OS }}"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: connection-strings-${{ env.OS }}

      - name: Wait until the ${{ env.OS }} servers are reacheable
        run: |
          python3 scripts/check_hosts.py --limit=${{ env.OS }}-webtunnel-client -i actions-inventory.ini

      - name: Test connections
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=test-webtunnel --limit=${{ env.OS }}-webtunnel-client -i actions-inventory.ini 

      - name: Shutdown ${{ env.OS }} servers
        run: |
          ./ansible-playbook.sh playbook.yaml --tags=shutdown-server --limit=${{ env.OS }} -i actions-inventory.ini

      - name: Delete ${{ env.OS }} webtunnel-client
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=delete-webtunnel-client -i actions-inventory.ini -e "os=${{ env.OS }}"

  setup-rhel:
    runs-on: self-hosted
    env:
      OS: rhel
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ${{ env.OS }} servers
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=create-server -i actions-inventory.ini -e "os=${{ env.OS }}"

      - name: Wait until the ${{ env.OS }} servers are reachable
        run: |
          python3 scripts/check_hosts.py --limit ${{ env.OS }} -i actions-inventory.ini

      - name: Run Ansible Playbook Test for ${{ env.OS }}
        run: |
          ./ansible-playbook.sh playbook.yaml --limit=${{ env.OS }} -i actions-inventory.ini

      - name: Upload connection-strings for ${{ env.OS }}
        uses: actions/upload-artifact@v4
        with:
          name: connection-strings-${{ env.OS }}
          path: connection-strings.txt

  test-rhel:
    needs: 
      - setup-rhel
    runs-on: self-hosted
    env:
      OS: rhel
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ${{ env.OS }} webtunnel-client
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=create-webtunnel-client -i actions-inventory.ini -e "os=${{ env.OS }}"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: connection-strings-${{ env.OS }}

      - name: Wait until the ${{ env.OS }} servers are reacheable
        run: |
          python3 scripts/check_hosts.py --limit=${{ env.OS }}-webtunnel-client -i actions-inventory.ini

      - name: Test connections
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=test-webtunnel --limit=${{ env.OS }}-webtunnel-client -i actions-inventory.ini 

      - name: Shutdown ${{ env.OS }} servers
        run: |
          ./ansible-playbook.sh playbook.yaml --tags=shutdown-server --limit=${{ env.OS }} -i actions-inventory.ini

      - name: Delete ${{ env.OS }} webtunnel-client
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=delete-webtunnel-client -i actions-inventory.ini -e "os=${{ env.OS }}"

  setup-suse:
    runs-on: self-hosted
    env:
      OS: suse
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ${{ env.OS }} servers
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=create-server -i actions-inventory.ini -e "os=${{ env.OS }}"

      - name: Wait until the ${{ env.OS }} servers are reachable
        run: |
          python3 scripts/check_hosts.py --limit ${{ env.OS }} -i actions-inventory.ini

      - name: Run Ansible Playbook Test for ${{ env.OS }}
        run: |
          ./ansible-playbook.sh playbook.yaml --limit=${{ env.OS }} -i actions-inventory.ini

      - name: Upload connection-strings for ${{ env.OS }}
        uses: actions/upload-artifact@v4
        with:
          name: connection-strings-${{ env.OS }}
          path: connection-strings.txt

  test-suse:
    needs: 
      - setup-suse
    runs-on: self-hosted
    env:
      OS: suse
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ${{ env.OS }} webtunnel-client
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=create-webtunnel-client -i actions-inventory.ini -e "os=${{ env.OS }}"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: connection-strings-${{ env.OS }}

      - name: Wait until the ${{ env.OS }} servers are reacheable
        run: |
          python3 scripts/check_hosts.py --limit=${{ env.OS }}-webtunnel-client -i actions-inventory.ini

      - name: Test connections
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=test-webtunnel --limit=${{ env.OS }}-webtunnel-client -i actions-inventory.ini 

      - name: Shutdown ${{ env.OS }} servers
        run: |
          ./ansible-playbook.sh playbook.yaml --tags=shutdown-server --limit=${{ env.OS }} -i actions-inventory.ini

      - name: Delete ${{ env.OS }} webtunnel-client
        run: |
          echo -e "\nANSIBLE_USER_PASSWORD=$ANSIBLE_USER_PASSWORD" >> .env
          ./ansible-playbook.sh actions-playbook.yaml --tags=delete-webtunnel-client -i actions-inventory.ini -e "os=${{ env.OS }}"