---

name: Update venv

on:
  schedule:
    - cron: '0 0 */3 * *'
  push:
    paths:
      - 'requirements.txt'
      - '.github/workflows/venv.yaml'

jobs:
  install-project-requirements:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create virtual environment
        run: python3 -m venv venv

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install ansible-galaxy requirements
        run: |
          source venv/bin/activate
          ansible-galaxy install -r requirements.yaml

      - name: Login to S3
        uses: mc-actions/configure@v1
        with:
          s3_server: '${{ secrets.S3_ENDPOINT }}'
          s3_access_key: '${{ secrets.S3_ACCESS_KEY }}'
          s3_secret_key: '${{ secrets.S3_SECRET_KEY }}'

      - name: Upload venv to S3
        shell: bash
        run: |
          mc cp -r venv/ default/actions-artifacts/venv/ >/dev/null && \
          echo "Uploaded venv successfully."
